---
title: "Imagine"
author: 
date: 
output: 
  html_document
runtime: shiny
css: imagine_style.css
---
<style>
body {
    position: absolute;
    left: 0px;}
</style>

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)

library(ggthemes)
library(ggplot2)
library(rethinking)
library(dplyr)
library(tidyr)

library(shinythemes, quietly =  TRUE)

library(BEST) # for posterior plot

# pirate plots
# install.packages("devtools") # Only if you don't have the devtools library already installed
   # library("devtools")
   # install_github("ndphillips/yarrr")

# library(yarrr)

options(digits = 3)
options(xtable.include.rownames=F)
```


```{r assumptions}


fluidPage(theme = shinytheme("flatly"), 
inputPanel(

  sliderInput("num_districts", label = "Number of districts",
              min = 2, max = 60, value = 2, step = 1, ticks = FALSE),
  
  sliderInput("n_clinics", label = "Number of clinics",
              min = 2, max = 60, value = 30, step = 5, ticks = FALSE),
  
  sliderInput("mean_population", label = "Average clinic size",
              min = 1000, max = 10000, value = 2500, step = 500, ticks = FALSE),
  
  sliderInput("bkrd_mean_incidence", label = "Average incidence / annum",
              min = .01, max = 1, value = .3, step = .1, ticks = FALSE),
  
  sliderInput("case.sensitivity", label = "Case detection sensitivity",
              min = .01, max = 1, value = 1, step = .1, ticks = FALSE),
  
   sliderInput("case.specificity", label = "Case detection specifiicty",
              min = .01, max = 1, value = 1, step = .1, ticks = FALSE),

   sliderInput("test.positive.rate", label = "Test positive rate",
              min = .01, max = 1, value = .5, step = .1, ticks = FALSE),
  
  sliderInput("reporting.fidelity", label = "Reporting fidelity",
              min = .01, max = 1, value = 1, step = .1, ticks = FALSE),
  
  sliderInput("effectiveness", label = "Intervention effectiveness",
              min = 0, max = 1, value = 0, step = .05, ticks = FALSE),
  
   selectInput("randomize", label = "Intervention randomized by",
              choices = c("clinic", "district"), selected = "clinic"),
  
   selectInput("analysis", label = "Analyis design",
              choices = c("randomized", "pre-post"), selected = "randomized"),
  
  actionButton("goButton", "Each press creates a trial",
               width = "100%"),

  actionButton("reset", "Clear"),
  
  selectInput("runs", label = "Number of runs",
              choices = c(100,1000,10000), selected = 100)

   
) 
, style='width: 1500px;'
)


```

```{r functions}

source('imagine_functions.R')

```

```{r data}
# DATA

c = reactive({
   if( input$goButton > 0){
      
   clinics(
           randomize = input$randomize,
           num_districts = input$num_districts  ,
           n_clinics = input$n_clinics  , 
           mean_population = input$mean_population 
           )
      }
})

d = reactive({
   if( input$goButton > 0){
      
   c =  isolate( c() )
   
   if ( input$analysis %in% "pre-post"){ 
      d = bind_rows(
         disease(
              clinic_list = c,
              bkrd_mean_incidence = input$bkrd_mean_incidence  ,
              case.sensitivity = input$case.sensitivity ,
              case.specificity = input$case.specificity ,
              test.positive.rate =  input$test.positive.rate ,
              reporting.fidelity = input$reporting.fidelity, 
              effectiveness = input$effectiveness,
              .period = 'pre'
              ), 
         disease(
              clinic_list = c,
              bkrd_mean_incidence = input$bkrd_mean_incidence  ,
              case.sensitivity = input$case.sensitivity ,
              case.specificity = input$case.specificity ,
              test.positive.rate =  input$test.positive.rate ,
              reporting.fidelity = input$reporting.fidelity, 
              effectiveness = input$effectiveness,
              .period = 'post'
              )
      )
      
   } else {
      d = disease(
              clinic_list = c,
              bkrd_mean_incidence = input$bkrd_mean_incidence  ,
              case.sensitivity = input$case.sensitivity ,
              case.specificity = input$case.specificity ,
              test.positive.rate =  input$test.positive.rate ,
              reporting.fidelity = input$reporting.fidelity, 
              effectiveness = input$effectiveness,
              .period = 'post'
              )
   }
      return(d)
}
})


eff = reactive({  
      if( input$goButton > 0){
         
         effect( d = d() , .analysis = input$analysis )
   }})

# initialize stored results for single runs...
values <- reactiveValues(df_data = NULL)

observeEvent(input$reset, {
    values$df_data <- NULL
  })  

df = reactive({
   
   if( input$goButton == 0) return()
   
   temp <- bind_cols(
      data.frame( interation = input$goButton ) ,
      as.data.frame( t(quantile(eff(), probs = seq(.025, .975, .475) )) )
   )
   
   if( input$goButton == 1 ){

      values$df_data <- temp

   } else {

      temp2 = isolate(values$df_data)
      values$df_data <- bind_rows( temp2 , temp )
   }
   
   return( values$df_data )
  })

# calculate long run data set 
long_run_data = reactive({ 

      if( input$goButton == 0) return()
   
      withProgress(message = 'Making plot', value = 0, {
      # Number of times we'll go through the loop

      runs = input$runs

      for ( i in 1:runs){

            c = clinics(
                 randomize = input$randomize,
                 num_districts = input$num_districts  ,
                 n_clinics = input$n_clinics  ,
                 mean_population = input$mean_population
                 )

            d = bind_rows(
                  disease(
                       clinic_list = c(),
                       bkrd_mean_incidence = input$bkrd_mean_incidence  ,
                       case.sensitivity = input$case.sensitivity ,
                       case.specificity = input$case.specificity ,
                       test.positive.rate =  input$test.positive.rate ,
                       reporting.fidelity = input$reporting.fidelity, 
                       effectiveness = input$effectiveness,
                       .period = 'pre'
                       ), 
                  disease(
                       clinic_list = c(),
                       bkrd_mean_incidence = input$bkrd_mean_incidence  ,
                       case.sensitivity = input$case.sensitivity ,
                       case.specificity = input$case.specificity ,
                       test.positive.rate =  input$test.positive.rate ,
                       reporting.fidelity = input$reporting.fidelity, 
                       effectiveness = input$effectiveness,
                       .period = 'post'
                       )
               )
            
         eff = effect( d = d , .analysis = input$analysis) # 

      temp <- bind_cols(
         data.frame( interation = i ) ,
         as.data.frame( t(quantile( eff, probs = seq(.025, .975, .475) )) )
      )

      if( i == 1 ){

         df_data <- temp

      } else {

         temp2 = df_data
         df_data <- bind_rows( temp2 , temp )
      }

      }

      return(df_data)

      # Increment the progress bar, and update the detail text.
      incProgress(1/runs, detail = paste("Doing part", i))
      }) # end withProgress

   })

long_run_data_summary = reactive({
    
   if( input$goButton == 0) return() 
   
   s = long_run_data() %>% 
      summarise(
         `% significant` = 100* sum( ifelse( `2.5%`>0 | `97.5%`<0, 1, 0) )/n(),
         `% sig positive` = 100 * sum( ifelse( `2.5%`>0 , 1, 0) )/n(),
         `% sig negative` = 100 * sum( ifelse( `97.5%`<0, 1, 0) )/n(),
         `mean of medians` = mean( `50%` )
      )
   
   return(s)
})

```


```{r display}
# summarise results
tabsetPanel(

tabPanel("Random Trial", 
fluidRow(
   
column(4, 

 renderPlot({
    
      if( input$goButton == 0) return()
    
      # pirateplot( cases ~ trt , data = d(), main = "Malaria cases at each clinic, by treatment group",
      #             theme.o = 3, point.o = .7, hdi.o = .5, bar.o = 0 )

   # plot( cases ~ factor(trt), data = d(),
   #       main = "Cases by treatment group", theme.o = 3, point.o = .7, hdi.o = .5,
   #       bar.o = 0 )

   
   # bwplot( cases ~ period.f|trt.f, data = d(),
   #         main = "Cases by treatment group", 
   #         layout=(c(1,2)) )
   
   ggplot( data = d() ) +
   geom_boxplot( aes( x = period.f, y = cases, group = period.f)) +
   facet_grid( trt.f ~ .) + 
   labs( x = 'Period', y = 'Cases') +
   theme_tufte()

   
   }),
 
 renderTable({
    
   if( input$goButton == 0) return()
    
  # d() %>% group_by(trt.f, period.f ) %>% arrange(trt.f, desc(period.f) ) %>%
  # summarise( 
  #    `no.clinics` = n(),
  #    `population` = mean(population),
  #    `bkrnd incidence` = mean(incidence),
  #    `sensitivity`= mean(sensitivity),
  #    `specificity`= mean(specificity),
  #    `cases`= round( mean(cases), 1 ) )

      
     if ( input$analysis %in% "pre-post"){
        d = d() %>%
        group_by( trt.f, period.f) 
     } else {
        d = d() %>% group_by( trt.f) 
     } 
    
   d = d %>%
   summarise( 
   n = n(),
   pop = sum(population), 
   total.cases = sum(cases),
   mean.cases = mean(cases)
) %>%
   mutate(
      dif = percent( ( lag(mean.cases, n = 1) - mean.cases ) / lag(mean.cases, n = 1) )
   )
   
   return(d)
  
})

),

column(4, 

renderPlot({

   if( input$goButton == 0) return()

   plotPost( eff() )

})

),

column(4,
 renderPlot({

      if( input$goButton == 0) return()

    ggplot( df() , aes( x = `50%`, y = interation )) +
    geom_point(size=5, shape=18) +
    geom_errorbarh(aes(xmax = `97.5%`, xmin = `2.5%`), height = 0.15) +
    geom_vline(xintercept = 0, linetype = "longdash") +
    scale_x_continuous( "Estimated effectiveness", limits = seq(-60,60, 120), breaks = seq(-50, 50, 10) ) +
    labs(y="")
    
   })
)

, style='width: 1200px;')
),

tabPanel("Example dataset", 
         renderTable( d()  )
) ,

tabPanel("Long Run", id = "longrun", 
         

   renderPlot({
      
   if( input$goButton == 0) return()

    ggplot( long_run_data() %>% arrange(-`50%`) %>% mutate( order = row_number()),
            aes( x = `50%`, y = order )) +
    geom_point(size=3, shape=18) +
    geom_errorbarh(aes(xmax = `97.5%`, xmin = `2.5%`), height = 0.15) +
    geom_vline(xintercept = 0, linetype = "longdash") +
    geom_vline(xintercept = input$effectiveness * 100, color = "green") +
    scale_x_continuous("Estimated effectiveness (median and 95% credible interval)", 
                       limits = seq(-60,60, 120), breaks = seq(-50, 50, 10) ) +
    labs(y="")


    }),
   
   renderTable( long_run_data_summary() )
   ),

tabPanel("Equations", 
         
         renderText({ "coming soon" })
         
         ),

tabPanel("Explanations",
         
         includeMarkdown("imagine_explanations.md")

)
)
         
```
